# Generated by Django 4.0.1 on 2022-01-15 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='time',
        ),
        migrations.AddField(
            model_name='class',
            name='endtime',
            field=models.TimeField(default='12:00', max_length=5),
        ),
        migrations.AddField(
            model_name='class',
            name='starttime',
            field=models.TimeField(default='12:00', max_length=5),
        ),
        migrations.AlterField(
            model_name='class',
            name='days',
            field=models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=5),
        ),
    ]
