# Generated by Django 4.0.1 on 2022-01-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_remove_class_time_class_endtime_class_starttime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='endtime',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='starttime',
            new_name='start',
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.CharField(default='John Smith', max_length=100),
        ),
    ]
