# Generated by Django 4.0.1 on 2022-01-15 02:38

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_rename_endtime_class_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=13),
        ),
    ]
