# Generated by Django 4.0.1 on 2022-01-15 02:40

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_class_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], max_length=13),
        ),
    ]
