# Generated by Django 4.0.1 on 2022-01-15 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_class_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='teacher',
            field=models.CharField(max_length=100),
        ),
    ]
