# Generated by Django 4.0.1 on 2022-01-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_class_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_type', models.CharField(choices=[(0, 'News Article'), (1, 'Announcement')], max_length=1)),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='class',
            name='end',
            field=models.TimeField(default='24:00', max_length=5),
        ),
        migrations.AlterField(
            model_name='class',
            name='start',
            field=models.TimeField(default='00:00', max_length=5),
        ),
    ]
