# Generated by Django 4.0.1 on 2022-01-17 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_article_alter_class_end_alter_class_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('news_article', 'News Article'), ('announcement', 'Announcement')], max_length=40),
        ),
    ]
